apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: mytask
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mytask
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi